### ISSUE TITLE
Items Repeater Sample using UniformGridLayout is incomplete

### ISSUE THREAD

**Issue by rafaels-dev** [microsoft/WinUI-Gallery#1073]
### Which version of the app?

WinUI 3 Gallery

### Description

I'm following the tutorial "[Create a simple Windows App with WinUI | CLL04](https://www.youtube.com/watch?v=FKuzzC-FFbQ)" and when I open the `ItemsRepeater` selecting the `UniformGridLayout` option, I can't see the C# code of the `BarItems` class.

### Screenshots

![image](https://user-images.githubusercontent.com/5066597/189503572-a1cb754c-1412-4e83-916f-0b2e350794db.png)

### Windows version

Windows 11 21H2 (22000)

### Additional context

WinUI Gallery version number: 1.3.15.0
Theme: Dark (using System Setting)

**Comment by jrbonell** [comment]
Same here.
The C# code sample is not present in the "Basic, non-interactive items laid out by ItemsRepeater" sample.

**Comment by X3vvv** [comment]
According to my experience using WinUI 3 Gallery, a number of example codes of the control elements are broken, which seems due to the github repository hosting the example codes has been changed by developers. And based on this guess, the developers didn't take it into consideration whether WinUI 3 Gallery can still work.

So although the examples display well in the gallery, the example codes snippets cannot work alone since it contain too many classes/variables that are defined in other files.

For example, as shown in the screenshot below, the Animation Interop's example code contains unknown references (marked in yellow).

![image](https://user-images.githubusercontent.com/65343237/206544095-f76bbf49-8f5f-4187-8f8f-42195baa9ba1.png)

**Comment by gregwoo-microsoft** [comment]
Thanks for your feedback @X3vvv. I will look more closely at these examples to fix this. Let us know if there are other samples like this that come to mind.

**Comment by gregwoo-microsoft** [comment]
I created PRs to improve both the ItemsRepeater & the AnimationInterop sample. I hope that this helps. Have a great weekend!
