### ISSUE TITLE
Add a link to style

### ISSUE THREAD

**Issue by niels9001** [microsoft/WinUI-Gallery#1124]
### Issue type

enhancement

### Which version of the app?

WinUI 3 Gallery

### Rationale
At times, developers want to re-template a control - if they use WinUI, they would need to use the XAML from the WinUI repo. Now this requires developers to manually go to the WinUI repo and look up the right file which takes time.

### Proposal
Add a link to every control page that directly links to the respective WinUI folder.

For instance, on the link on the Infobar page would target: https://github.com/microsoft/microsoft-ui-xaml/tree/main/dev/InfoBar

**Comment by gregwoo-microsoft** [comment]
Love the idea, thanks @niels9001

**Comment by chingucoding** [comment]
I think this is a reasonable request, however I am not sure if this does not add more confusion to the WinUI 3/WinUI 2 confusion. Pointing devs to the WinUI 2 source code since they clicked on a link in the WinUI 3 Gallery seems a bit misleading. What do you think @gregwoo-microsoft @niels9001 @bpulliam .

Implementation wise, I think we need an additional field in the controls.json file since the scheme for the controls is homogenous and has some exceptions instead.

**Comment by bpulliam** [comment]
I agree that this makes sense at first glance, but that it will eventually cause confusion. The code for WinUI3 is the same, except when it isn't.  Once we get the WinUI3 source available in the open (it is still a goal!) we should absolutely do this, but until then, I think we should wait.

**Comment by karkarl** [comment]
With the WASDK source now publicly available, this is an opportunity to link the code to that.

**Comment by niels9001** [comment]
Closing this in favor of: #1388
