### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by Natriss** [microsoft/WinUI-Gallery#1595]
### Which version of the app?

WinUI 3 Gallery

### Description

![image](https://github.com/user-attachments/assets/6066b618-d7f4-4b91-9be5-1398b026d53b)
![image](https://github.com/user-attachments/assets/d3111d10-949b-44e5-ae61-faf55536e2d1)

These are just 2 icons that are missing from the list.
The 2 arrows should be E174 but I don't know the brush one.
Is it possible to find all the available icons or is that available list depended on the Microsoft Docs page?

I reported this also to the Microsoft Docs https://github.com/MicrosoftDocs/windows-dev-docs/issues/5078#issue-2430449053

### Windows version

Windows 11 23H2 (22631)

**Comment by karkarl** [comment]
Upon some research, it seems the icons above are part of the fluent icon set, but not shipped as part of the Windows MDL2 font set. Thus, it is not documented because it is not available. I'm glad you also filed an issue with the docs repo, since it will be good for the documentation to explain these differences.
