### ISSUE TITLE
AnnotatedScrollBar thumb has narrow range of movement

### ISSUE THREAD

**Issue by hyam1567** [microsoft/WinUI-Gallery#1613]
### Which version of the app?

WinUI 3 Gallery

### Description

Problem with AnnotatedScrollBar page in WinUI 3 Gallery.
When I try to move the thumb down, it doesn't move to the bottom position.

### Screenshots

![AnnotatedScrollBar thumb has narrow range of movement](https://github.com/user-attachments/assets/314704a6-0123-4520-b53b-8d8979d33443)

### Windows version

Windows 11 22H2 (22621)

**Comment by ojhad** [comment]
This is by design. The gap represents the viewport height. This is important for scenarios where the AnnotatedScrollbar needs to display labels for content that is located somewhere past the point where scrolling ends. As an example, if in your screenshot above, the last 3 rows were Green, the 'Green' label would be displayed in the gap.

**Comment by hyam1567** [comment]
I see.
But it seems unnatural.
I think it would be improved if the thumb had a length like a normal scrollbar.
