### ISSUE TITLE
NavigationView > "API in action" has bugs

### ISSUE THREAD

**Issue by kmgallahan** [microsoft/WinUI-Gallery#225]
**Describe the bug**
Checking and unchecking different boxes puts the NavigationView in unexpected states.

**Steps to reproduce the bugs**
Open the XAML Controls Gallery > Navigation > NavigationView > API in action. Bugs:

- Change to PanePosition Top > change to PanePosition Left > Pane Title & Hamburger menu are in a new location > collapse the NavigationView > they move
- Uncheck AutoSuggestBox visible > there is still a vertical gap for it > uncheck Settings item visible > the gap is gone > check AutoSuggestBox > it doesn't display > check Settings item visible > it shows again
- Uncheck AutoSuggestBox > Collapse NavigationView > search icon is still displayed
- Back button doesn't appear to function (might be intentional)

Gallery version (found on Settings page): 
1.2.10.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [X] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Comment by chingucoding** [comment]
I have looked into this, and I think that this are not issues caused by the XCG, but rather bugs in the NavigationView itsself (except the 4th point). So here a short summary of the issues, and why I think that the bugs are in WinUI:

1. Switching display mode and forcing pane to be open in left mode:
  Setting the display mode to left and opening the pane should NOT result in the pane header behaving as if it where in minimal mode.

2. (Un)checking AutoSuggestBox is buggy
Updating the AutoSuggestBox of the NavigationView (which is build in feature of the NavigationView (at least partially)), should also cause a rerendering IMO, as this is a property of the NavigationView, so us changing this is something the NavigationView should respect and update accordingly.

3. Removing AutoSuggestBox shows the icon in compact mode
I think this is related to point 2. As the NavigationView seems to have trouble dealing with updates to the AutoSuggestBox property of itsself, not knowing when to show/hide the icon seems to be logical, but wrong behavior.

4. Back button having no effect
I have no idea why this has no effect 😅

@stmoy , @YuliKl Should we move this issue to WinUI or create issues for those bugs over there?

**Comment by bpulliam** [comment]
no repro on current builds.
