### ISSUE TITLE
I'd appreciate a scheduler sample

### ISSUE THREAD

**Issue by iamalexmang** [microsoft/WinUI-Gallery#231]
I tried several times to come up with a decent and good looking scheduler, one that resembles the app where I could have a month view and a week view.
Regretfully, my attempts have failed thus far and the components coming from 3rd party vendors are seriously not treating WinUI right, trying to have a good chunk of the entire Fluent Design redefined by someones else's sense of functional layouts and own subjective taste - there's always an unnatural feeling of inconsistency when using them. Hence the reason for why a Scheduler component would be more than welcome and a absolutely highly appreciate add.

**Describe the sample**
Looking at the Calendar app's layout, my expectation is for a Scheduler component to allow through a property to change the layout to a day, week, workweek or month view. In each of these cases, a layout would be displayed which shows the existing appointments. IMHO, an appointment would be an abstract class' visual representation, where a few things would need to exist: start time, end time, recurrence (CRON expression - maybe), time zone, title and location and description. Anything else would be part of its extensibility model, but this at least would be the bare minimum necessary.
The layout itself would allow for both vertical and horizontal scrolling to scroll through the day(s) - on vertical scrolling and through the days/weeks/months (depending on the chosen layout) on horizontal scrolling.
Another scheduler property would allow for the work times and days to be set and these would be highlighted in the UI.

**Comment by chingucoding** [comment]
Is this about an existing component, such as Button or GridView, or is this about a "new" component that does not exist in WinUI? 😅

**Comment by amang2205** [comment]
New component or sample.

**Comment by stmoy** [comment]
This is an interesting idea! @amang2205, if I understand correctly, it sounds like you're envisioning a more complete sample than a small component like a CalendarView sample -- is that correct? Or are you requesting a "Scheduler" widget that is similar to CalendarView, but more fully featured (ie. fills the whole screen, etc.)? 

Historically, we've had complete app samples exist in their own repo: https://github.com/microsoft/Windows-universal-samples/tree/master/Samples

Perhaps a complete scheduler sample might feel more at home in that repo? Or, if it's a "widget", would this be more at home on the WinUI repo?

**Comment by amang2205** [comment]
Are you sure that this was in the Windows-universal-samples repo?
Maybe I wasn't specific enough, so please allow me to explain this again.
I've researched for a while options to get a reasonably good looking, intuitive and native/natural looking calendar, but the issue with using the word calendar is that most people immediately think of a calendar date/picker. That sample is indeed available in the XAML Controls Gallery.

This sample I'm envisioning could work either as a component by itself (that would be really great) and that's exactly what some component libraries have tried before. However, since the extensible points and potential bindings are... well, a lot, I also believe that a sample would definitely help.
This sample would highlight the representation of Appointments (including the representation of overlapping appointments) the various layouts, animations and all the Fluent Design language put in practice.

On the other hand though, if the Calendar app would be open-sourced, we'd already have an amazingly good starting point for this type of a somewhat more complex scenario.

**Comment by chingucoding** [comment]
I think this is request, if this control/sample is still requested, would be a lot better suited for the [WinUI](https://github-com/microsoft/microsoft-ui-xaml) or the Windows-Universal-Sampels repo. Closing this issue as stale now.

**Comment by iamalexmang** [comment]
I understand that the issue was/is stale, but I had it opened after talking to your colleagues in the Windows development team, suggesting that the Calendar app cannot (by that time) be made open source to highlight the scheduler implementation and suggesting the request for such a component instead. 

Three years later and the open source components are still terrible, the FluentUI implementation lacks a reasonable and decent scheduler suggestion and this issue which I had high hopes for is closed due to inactivity 🥺.

**Comment by chingucoding** [comment]
I totally understand your frustration around this and if you like, I can reopen this issue. However, this repository is for the WinUI Gallery which is designed to show case controls/components and features of WinUI 3/WinAppSDK. While I totally understand that you would like such a sample, I think this would be out of scope for this repository since it not existing functionality but rather a new control that would be developed. This is also why requesting this on the WinUI repository or the Windows-Universal-Samples repo will likely get more traction than raising this here.

PS: I'm not working for Microsoft.
Also @gregwoo-microsoft FYI.

**Comment by gregwoo-microsoft** [comment]
+1 to what @chingucoding said. If you would like to request a brand new control, then the [WinUI ](https://github.com/microsoft/microsoft-ui-xaml)repo is the best place to do that. On the other hand, if you would like to request a more advanced sample using existing controls, then I would suggest that you file an issue on the [WASDK Samples](https://github.com/microsoft/WindowsAppSDK-Samples) repo. I hope that this helps :)
