### ISSUE TITLE
Rounded Corners Sample

### ISSUE THREAD

**Issue by stmoy** [microsoft/WinUI-Gallery#375]
**Is this a totally new sample, an addition to an existing sample page, or a modification of an existing sample page?**
- [x] New sample
- [ ] Addition to existing sample
- [ ] Modification to existing sample

**If this is an addition/modification to an existing sample page, which one?**

**Describe the sample**

Add a new sample that shows off:
1. Rounded corners on a set of existing controls
1. How to customize rounded corners
1. How to turn off rounded corners if necessary

Consider adding a link to the Xaml Fluent Theme Editor which also supports these scenarios. 

**Is your sample request related to a problem? Please describe it**

**Additional context**

**Comment by Chips1234** [comment]
I would like to work on this, just telling everyone

**Comment by stmoy** [comment]
@Chips1234 - fantastic! Please reach out if you have any questions 😁

CC: @chigy @kikisaints for FYI

**Comment by Chips1234** [comment]
Alright.

**Comment by Chips1234** [comment]
Alright. Thanks. One problem is, how do I get rid of light-up when the textbox comes into focus? I put it into a border but the highlight is a problem (see picture)
![Txt no radius](https://user-images.githubusercontent.com/47545798/87501675-84ed2100-c614-11ea-8167-ede28cb83e2d.jpg)

**Comment by chigy** [comment]
> Alright. Thanks. One problem is, how do I get rid of light-up when the textbox comes into focus? I put it into a border but the highlight is a problem (see picture)
> ![Txt no radius](https://user-images.githubusercontent.com/47545798/87501675-84ed2100-c614-11ea-8167-ede28cb83e2d.jpg)

@Chips1234 , could you tell me why you are trying to do that? We should just show rounding of the corner of the light-up and not start redesigning the control with this effort.

**Comment by Chips1234** [comment]
I’m trying to put it into a border as shown [here](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.cornerradius?view=winrt-19041). I tried `CornerRadius` within the text box but an error says that “CornerRadius” does not support older versions of Win10.

**Comment by chigy** [comment]
@Chips1234 , I wanted to share how we do work for WinUI in terms of how each sample apps and documents are connected and we use them to help developers/designers. I thought this is important for you to be aware as you investigate the work you would work on this proposal.

This proposal touches on 3 ways we communicate with our developer/designer audiences:
- Documentation - https://docs.microsoft.com/en-us/windows/uwp/design/style/rounded-corner
  - We document the guidance, sample code, etc. so that developer and designer audiences know how to use them properly. For this effort, we'd like to make sure the sample you write in Controls Gallery match that of sample shared in this doc. If you require to write additional code, we want to make sure we consider updating the guidance.
- Controls Gallery - This is our "live" sharing of the controls and guidance. 
  - Idea is that we are releasing examples and samples that match what we talk about in the above documentation. We also take screenshots of the samples to use them in the documentation so we want to make sure samples produce quality examples.
- Theme Editor - This app let designer/developer to create a visual using the properties we expose to create types of UI customization that still ensure not deviating too much to require retemplating. 
  - Idea is that the type of sample code you wrote in Controls Gallery are things users of Theme Editor can see updated automatically.

Let me know if you have any questions about this.

**Comment by chigy** [comment]
@kikisaints , please take a look and comment on @Chips1234 comment here?

>I’m trying to put it into a border as shown here. I tried CornerRadius within the text box but an error says that “CornerRadius” does not support older versions of Win10.

**Comment by Chips1234** [comment]
@stmoy So you want a separate page on corner radius or do you just want a new example in the existing pages?

**Comment by chingucoding** [comment]
I think a separate page would be the best for this,

**Comment by Chips1234** [comment]
Ok

________________________________

**Comment by Chips1234** [comment]
Ok, so I have here a new Xaml document, `CornerRadiusPage.xaml`. In the json, I have:
```json
{
          "UniqueId": "CornerRadius",
          "Title": "CornerRadius",
          "Subtitle": "Lorem",
          "ImagePath": "ms-appx:///Assets/DefaultIcon.png",
          "Description": "Lorem",
          "Content": "Lorem",
          "IsNew": true,
          "Docs": [
            {
              "Title": "ParallaxView - API",
              "Uri": ""
            },
            {
              "Title": "Guidelines",
              "Uri": ""
            }
          ],
          "RelatedControls": [

          ]
        }
```

But how do I link it to the XAML page? It does nothing when I click on it. Thanks!

**Comment by Chips1234** [comment]
@chigy If I set CornerRadius, I get this: Warning, XLS1105, The property ‘CornerRadius’ on type ‘Button’ is not available in the target platform minimum version (10.0.17134.0) supported by this project. I can set a conditional namespace though, is that what you want me to do?

**Comment by stmoy** [comment]
> I think a separate page would be the best for this,

+1 

> I can set a conditional namespace though, is that what you want me to do?

Conditional Xaml would be the appropriate way to handle this, yes. In addition, please be sure to set the `MinimumUniversalAPIContract` on the ControlExample.

**Comment by Chips1234** [comment]
Ok

________________________________

**Comment by Jay-o-Way** [comment]
Is this still an issue with the latest version?

**Comment by chingucoding** [comment]
@jay-o-way I'm pretty sure this is still relevant given there exists no sample that I know of that showcases this.

**Comment by niels9001** [comment]
Closing this as resolved since we have the Geometry page in the design section that explains the different CornerRadius resources that ship with WinUI.
