### ISSUE TITLE
Update XCG winui3 (PR 0.8) to 1.0

### ISSUE THREAD

**Issue by asklar** [microsoft/WinUI-Gallery#821]
Update the winui3 gallery to use winappsdk 1.0
Code lives at https://github.com/microsoft/Xaml-Controls-Gallery/tree/winui3/XamlControlsGallery

**Comment by chingucoding** [comment]
@gregwoo-microsoft Mind if I take my shot at it (assuming you, @asklar don't want to).

**Comment by asklar** [comment]
no complaints from me :D

**Comment by chingucoding** [comment]
Taking a quick look at the project files though, I'm a bit confused as to if all those if defs for different packages (and presumably local development) are still desired or if they can be removed. Maybe @RealTommyKlein knows more about this?

**Comment by gregwoo-microsoft** [comment]
@asklar we are currently working on updating the WinUI 3 Controls Gallery. A new update should be out soon. Stay tuned! :)

**Comment by RealTommyKlein** [comment]
Back in the virtual office tomorrow - think I need to sync with @gregwoo-microsoft to ensure we also have a good way of building the new unpackaged version of XamlControlsGallery (our current private version which hasn't been pushed to this repo yet involves a build script instead of a nice F5'able project in VS), and that we port #786 to the current private XamlControlsGallery so it doesn't get paved over when pushing to the public repo.

> Taking a quick look at the project files though, I'm a bit confused as to if all those if defs for different packages (and presumably local development) are still desired or if they can be removed. Maybe @RealTommyKlein knows more about this?

@chingucoding - correct, we still need those `#ifdef`s and project build properties :smile: .  XamlControlsGallery has some other  build modes only relevant for our private inner-loop testing (like targeting locally built WinUI binaries instead of the `Microsoft.WindowsAppSDK` NuGet package).

**Comment by seven-mile** [comment]
> @asklar we are currently working on updating the WinUI 3 Controls Gallery. A new update should be out soon. Stay tuned! :)

Will it come out before 2022?😉

**Comment by gregwoo-microsoft** [comment]
Yes @seven-mile ! In fact, the new version of the WinUI 3 Controls Gallery is out in the Store right now! It uses the WinAppSDK 1.0 that was recently released + a bunch of control updates. We will update the code on the WinUI 3 branch in early Jan as we are still working out some small details.

**Comment by SkyIsWhite** [comment]
> 

i have already found the new WinUI 3 Controls Gallery that uses the WinAppSDK 1.0 but i can't found the source

**Comment by SkyIsWhite** [comment]
> Yes @seven-mile ! In fact, the new version of the WinUI 3 Controls Gallery is out in the Store right now! It uses the WinAppSDK 1.0 that was recently released + a bunch of control updates. We will update the code on the WinUI 3 branch in early Jan as we are still working out some small details.

i have already found the new WinUI 3 Controls Gallery that uses the WinAppSDK 1.0 but i can't found the source

**Comment by gregwoo-microsoft** [comment]
Yes @skyiswhite, the new version was released to the store but the source code isn't released yet to the public repo. We are fixing a few additional bugs internally before we update it here. Should be accessible pretty soon. I'll update this thread when the source code is out.
